### PR TITLE
Fullscreen Planner Dashboard Fix

### LINKED ISSUE #289: Fullscreen Planner Dashboard
# Scope

Make planner dashboard resize to fill whole screen.

### PR DESCRIPTION
**Pull request by zacktraczyk**
# Scope

Fullscreen dashboard to size with browser window. Closes #289. Before change:

Screenshot 2024-02-26 at 9 20 14 PM

# Implementation

Created flex box sizing on divs. After change:

Screenshot 2024-02-26 at 9 22 00 PM

### CODE REVIEW

File: src/app/components/planners/PlannerList.tsx [hunk 1]
```diff
@@ -13,25 +13,25 @@ export default function PlannerList() {
 
   if (!planners || planners.length == 0) return <HelpfulTips />;
 
+  // Why using map? Why not just render the Planner component directly?
```
Comment (fercevik729) [inline src/app/components/planners/PlannerList.tsx:16]: Because we need to include the providers with their props. We can move these providers into Planner but then we'd need to give it an `id` prop. This might be better though.

File: src/lib/utils.ts [hunk 2]
```diff
@@ -3,11 +3,26 @@ import { Course } from "@prisma/client";
...
 export const zip = (arr1: any[], arr2: any[]) => {
   return arr1.map((elem, index) => [elem, arr2[index]]);
 };
 
 // Utility function to truncate tab title
+
+/**
+ * Truncates a title to a certain length
+ *
+ * NOTE: There is also a tailwindCSS class for this (truncate)
```
Comment (fercevik729) [inline src/lib/utils.ts:21]: Awesome. Let's refactor the old code that uses this function where the tailwind utility class can be used.

File: src/lib/utils.ts [hunk 3]
```diff
@@ -3,11 +3,26 @@ import { Course } from "@prisma/client";
...
+ * Zips two arrays together
+ * @param arr1 First array
+ * @param arr2 Second array
+ * @returns zip of two arrays
+ */
 export const zip = (arr1: any[], arr2: any[]) => {
   return arr1.map((elem, index) => [elem, arr2[index]]);
 };
 
 // Utility function to truncate tab title
```
Comment (fercevik729) [inline src/lib/utils.ts:16]: Remove this comment

File: src/app/components/planners/PlannerList.tsx (hunk 1 above)
Comment (zacktraczyk) [reply src/app/components/planners/PlannerList.tsx:16]: I'm gonna wait to see if this is something we can do away with Zustand, not sure its worth the refactor if its going to be refactored again soon.

I definitely see the need for Zustand while working through this component, I had to work through a lot of wrapping divs that were only there for providers and other non-ui elements, ideally we would simplify this at some point if possible.

File: src/lib/utils.ts (hunk 2 above)
Comment (zacktraczyk) [reply src/lib/utils.ts:21]: My bad, the way you are using it is different than the tailwindcss class I should have taken a closer look.

[CSS Truncate](https://tailwindcss.com/docs/text-overflow) just adds ellipses only in the UI, it does not mutate the actual string. I see that your mutating the string and saving it with ellipses which is different behavior.

I am a bit reluctant to chase down all the providers / hooks to see if not mutating the string throws any errors (I can already seen in one case that `truncteTitle` enforces a description max length).

**Review by fercevik729 — APPROVED** [review]
